"""결과물 커밋 → PR 생성 → 리뷰어 요청"""
import subprocess
import time
from pathlib import Path
from github import Github, GithubException
from src.config import settings


def _git(args: list[str], cwd: Path) -> str:
    r = subprocess.run(["git"] + args, cwd=cwd, capture_output=True, text=True)
    return r.stdout.strip()


def _full_repo(repo: str) -> str:
    return repo if "/" in repo else f"{settings.github_owner}/{repo}"


async def commit_and_pr(
    worktree: Path,
    repo_name: str,
    base_branch: str,
    skill_name: str,
    report: str,
    reviewers: list[str] | None = None,
) -> dict:
    """워크트리 변경사항을 커밋하고 GitHub PR을 생성한다."""
    full_repo = _full_repo(repo_name)
    new_branch = f"jarvis/{skill_name}-{int(time.time())}"
    scope = skill_name.split("-")[0]

    _git(["config", "user.email", "jarvis@team.local"], worktree)
    _git(["config", "user.name", "Jarvis"], worktree)
    _git(["checkout", "-b", new_branch], worktree)
    _git(["add", "-A"], worktree)

    status = _git(["status", "--short"], worktree)
    if not status:
        return {"pr_url": None, "changed": False, "branch": new_branch}

    commit_msg = f"chore({scope}): apply {skill_name}"
    _git(["commit", "-m", commit_msg], worktree)
    _git(["push", "origin", new_branch], worktree)

    g = Github(settings.github_token)
    repo = g.get_repo(full_repo)

    pr_body = (
        f"## Jarvis Auto PR\n\n"
        f"**Skill:** `{skill_name}`  \n"
        f"**Base:** `{base_branch}` ← `{new_branch}`\n\n"
        f"### Report\n```\n{report[:3000]}\n```\n\n"
        f"_Generated by Jarvis 🤖_"
    )
    pr = repo.create_pull(
        title=commit_msg,
        body=pr_body,
        head=new_branch,
        base=base_branch,
    )

    if reviewers:
        # Slack @mention → GitHub username 변환 (단순 strip)
        github_users = [r.strip("@").split("|")[-1] for r in reviewers if r.strip("@")]
        try:
            pr.create_review_request(reviewers=github_users)
        except GithubException:
            pass

    return {"pr_url": pr.html_url, "pr_number": pr.number, "branch": new_branch, "changed": True}
